"use client";

import React, { useState } from "react";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, Modal, Button } from "antd";
import NavHeader from "@/components/layout/header";
import antdTheme from "@/utils/config/antdConfig";
import FooterComp from "@/components/layout/footer";
import favicon from "../assets/images/eco-mama.png";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isModalVisible, setIsModalVisible] = useState(false);

  const showModal = () => setIsModalVisible(true);
  const handleClose = () => setIsModalVisible(false);

  return (
    <html lang="en">
      <head>
        <link rel="icon"  />
        <title>Eco-Mama</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConfigProvider theme={antdTheme}>
          <NavHeader />
          {/* <Button onClick={showModal} type="primary" style={{ margin: "20px" }}>
            Open Cody AI Chatbot
          </Button> */}
          <Modal
            title="Cody AI Chatbot"
            visible={isModalVisible}
            onCancel={handleClose}
            footer={null}
            width="100%"
            style={{ maxWidth: "800px" }}
          >
            <iframe
              src="https://embed.cody.bot/9d54bf22-8e62-4c98-8a90-ad00912fe731"
              title="Cody AI Chatbot"
              style={{ border: 0, width: "100%", height: "600px" }}
              name="codyai"
              scrolling="no"
              frameBorder="1"
              allowFullScreen
            ></iframe>
          </Modal>
          <AntdRegistry>{children}</AntdRegistry>
          <FooterComp />
        </ConfigProvider>
        <script dangerouslySetInnerHTML={{
          __html: `
            window.codySettings = { widget_id: '9d54bf22-8e62-4c98-8a90-ad00912fe731' };
            (function(){
              var t = window, e = document, a = function() {
                var t = e.createElement("script");
                t.type = "text/javascript";
                t.async = true;
                t.src = "https://trinketsofcody.com/cody-widget.js";
                var a = e.getElementsByTagName("script")[0];
                a.parentNode.insertBefore(t, a);
              };
              if (document.readyState === "complete") a();
              else if (t.attachEvent) t.attachEvent("onload", a);
              else t.addEventListener("load", a, false);
            })();
          `,
        }} />
      </body>
    </html>
  );
}
